### ISSUE TITLE
Android手机，更新到最新代码，当页面存在ccui.EditBox编辑控件节点时，锁屏再进入页面

### ISSUE THREAD

**Issue by chackist** [u0u0/Quick-Cocos2dx-Community#100]
Android手机，更新到最新代码，当页面存在ccui.EditBox编辑控件节点时，锁屏再进入页面，点击编辑控件，输入面板无法弹出。各位都试试，如果有正常的，也麻烦告知。

**Comment by chackist** [comment]
补充一下，游戏是横屏的情况下，看了下日志，是因为恢复的时候activity生命周期走了两次

**Comment by Maxize** [comment]
如果是 activity 走两次的问题，找一下关于 android 横竖切换的 bug 就能解决了。[Android 横竖屏切换](https://www.jianshu.com/p/dbc7e81aead2)

**Comment by u0u0** [comment]
暂未遇到

**Comment by chackist** [comment]
close
