### ISSUE TITLE
scheduleUpdate的bug

### ISSUE THREAD

**Issue by panhaozi** [u0u0/Quick-Cocos2dx-Community#102]
NodeEx中有个scheduleUpdate函数，一般情况下工作正常，但有些例外：
1.如果这个Node是放在display.getRunningScene()中，这种情况下这个函数无法工作
2.如果这个Node是ccui.ScrollView，也无法工作

**Comment by u0u0** [comment]
1.确保 display.getRunningScene() 是有返回值，这样就能工作。
2.确实ccui.ScrollView或ccui.PageView等，在c++重写了update()函数的，会导lua帧毁掉丢失。
   暂时不考虑修正这个问题，注意下使用情况就好。
