### ISSUE TITLE
为什么注释掉这行？

### ISSUE THREAD

**Issue by feng20068** [u0u0/Quick-Cocos2dx-Community#104]
https://github.com/u0u0/Quick-Cocos2dx-Community/blob/e438a7108d928d4b544a5b2e13423678a4633e3d/quick/lib/quick-src/extra/platform/android/CCHTTPRequestAndroid.cpp#L227

注释后有多个请求时会挂掉
libc: pthread_create failed: couldn't allocate 1036288-bytes mapped space: Out of memory

**Comment by u0u0** [comment]
已修正。
