### ISSUE TITLE
关于安卓API LEVEL升级到26的方法

### ISSUE THREAD

**Issue by pandaGames** [u0u0/Quick-Cocos2dx-Community#117]
请问如何把API LEVEL升级到26？简单的配置build.gradle文件好像不太行，一直编译不通过……

> 自2019年8月1日起，现有应用的更新应基于Android 8.0 （API等级26）及以上开发。八家厂商在签约仪式上郑重承诺：将严格遵守和履行自律公约规定，拒绝上架和更新低API等级应用。

相关链接：[TAF WG4 2018年第三次工作组会议暨《移动应用软件高API等级预置与分发自律公约》签约仪式成功举办](http://www.taf.org.cn/News_detail.aspx?_NOTICE_ID=230)

**Comment by mr-bogey** [comment]
> 请问如何把API LEVEL升级到26？简单的配置build.gradle文件好像不太行，一直编译不通过……
> 
> > 自2019年8月1日起，现有应用的更新应基于Android 8.0 （API等级26）及以上开发。八家厂商在签约仪式上郑重承诺：将严格遵守和履行自律公约规定，拒绝上架和更新低API等级应用。
> 
> 相关链接：[TAF WG4 2018年第三次工作组会议暨《移动应用软件高API等级预置与分发自律公约》签约仪式成功举办](http://www.taf.org.cn/News_detail.aspx?_NOTICE_ID=230)

[app](https://github.com/mr-bogey/base/blob/master/frameworks/runtime-src/proj.android/app/build.gradle)
[cocos2dx](https://github.com/mr-bogey/base/blob/master/frameworks/runtime-src/proj.android/libcocos2dx/build.gradle)
应该不存在问题啊

**Comment by u0u0** [comment]
两个 build.gradle 的targetSdkVersion 改为 26
更具AS提示，一路fix，没有问题。
