### ISSUE TITLE
curl 的多线程请求 https 崩溃问题

### ISSUE THREAD

**Issue by shengdoushi** [u0u0/Quick-Cocos2dx-Community#120]
测试版本 Quick-Cocos2dx-Community 3.7.6，

在多线程请求 https 时候会崩溃在 curl_easy_perform (HTTPRequest 内部). 

可以通过下面代码测试重现（适当调高数值更易重现）。

```lua
   local url="https://www.baidu.com"
   for i =1,100 do
      local request = network.createHTTPRequest(function()
						end, url, "GET")
      request:start()
   end
```

http 没有此问题

**Comment by shengdoushi** [comment]
ios 模拟器上测试的

**Comment by shengdoushi** [comment]
使用 https://curl.haxx.se/mail/lib-2012-03/0009.html 里的解决方案测试了下，可以修复此问题

**Comment by u0u0** [comment]
fixed
