### ISSUE TITLE
quick/lib/quick-src 代码建议独立成库

### ISSUE THREAD

**Issue by shengdoushi** [u0u0/Quick-Cocos2dx-Community#124]
当前是直接以源代码方式加入到客户工程中去。是否以库的形式组织一下，以类型 cocos2d, luacocos2d 的库形式组织并集成。

好处如下：
1. 工程组织清晰，这样用户的主工程是其业务代码
2. 减轻引擎升级部署，当 quick-src 代码有调整时，无需更改用户的主工程

**Comment by u0u0** [comment]
4.0 已改变～
