### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by killer3392** [u0u0/Quick-Cocos2dx-Community#125]
我执行了setup_mac.sh，但是安装失败了，系统10.14.5
zhouxindeMacBook-Pro:Quick-Cocos2dx-Community-master zhouxin$ sh setup_mac.sh 

QUICK_V3_ROOT = "/Users/zhouxin/Documents/Quick-Cocos2dx-Community-master"

> Xcode settings updated.
> Quick player settings updated.
> Setup evn for shell:/bin/bash
> /Users/zhouxin/.bash_profile updated.
> ~/.QUICK_V3_ROOT updated.

Password:
cp: /Users/zhouxin/Documents/Quick-Cocos2dx-Community-master/quick/player/player3.app: No such file or directory
chmod: /Users/zhouxin/Documents/Quick-Cocos2dx-Community-master/quick/player/player3.app: No such file or directory
chmod: /Applications/player3.app: No such file or directory
Player3 has installed in /Applications

done. Please restart shell to make QUICK_V3_ROOT work

zhouxindeMacBook-Pro:Quick-Cocos2dx-Community-master zhouxin$

**Comment by u0u0** [comment]
github上没有预编译的bin，请在社区主页上下载zip发布包。或自行编译。
