### ISSUE TITLE
win32-msvc-2013-x86.cmd and win32-msvc-2012-x86.cmd  can not run correctlly 

### ISSUE THREAD

**Issue by lbfamous** [u0u0/Quick-Cocos2dx-Community#13]
Error :
CMake Error: The source directory "D:/repo/Quick-Cocos2dx-Community" does not ap
pear to contain CMakeLists.txt.

D:/repo is my project directory

I thin you remove CMakeLists.txt from the main directory

**Comment by u0u0** [comment]
Thanks for your report.
Before fix this issue, i need check if win32-msvc-2013-x86.cmd & win32-msvc-2012-x86.cmd are necessary for Quick.

**Comment by u0u0** [comment]
quick has no test sets that cocos2d-x has,  those build scriot will be deleted in 3.6.1
