### ISSUE TITLE
mac 安装失败

### ISSUE THREAD

**Issue by AriaLyy** [u0u0/Quick-Cocos2dx-Community#132]
按照文档设置了路径，还是找不到路径！！！
![image](https://user-images.githubusercontent.com/10437293/63155869-1095b080-c046-11e9-954e-67953c3bed83.png)

**Comment by AriaLyy** [comment]
看到 issue https://github.com/u0u0/Quick-Cocos2dx-Community/issues/125 ,请问bin是什么东西？在哪下载，文档在哪？

**Comment by u0u0** [comment]
http://www.cocos2d-lua.org/download/index.md
