### ISSUE TITLE
Quick-Cocos2dx-Community 3.6.5的百度盘地址失效了能帮助补充链接吗

### ISSUE THREAD

**Issue by haoqoo** [u0u0/Quick-Cocos2dx-Community#145]
Quick-Cocos2dx-Community 3.6.5 Release Note
下载地址**:https://pan.baidu.com/s/1qYCq5bQ**  已失效

shasum -t 512: 27e1f9b34f8e7c63760d7c0054653c86d41940db

**Comment by 794364474** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。
