### ISSUE TITLE
Quick-Cocos2dx-Community 3.6.5的百度盘地址失效了能帮助补充链接吗

### ISSUE THREAD

**Issue by haoqoo** [u0u0/Quick-Cocos2dx-Community#146]
大佬，Quick-Cocos2dx-Community 3.6.5的百度盘地址失效了，能帮助补充链接吗？

以前下载地址:https://pan.baidu.com/s/1qYCq5bQ，打不开。

**Comment by u0u0** [comment]
加群361920466
