### ISSUE TITLE
win10在编译期间抛异常

### ISSUE THREAD

**Issue by colorwu76** [u0u0/Quick-Cocos2dx-Community#147]
proj.android.cwdz.main | debug | arm64-v8a Compiler exited with error code 1: 
C:\Users\admin\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe 
-xc++ --target=aarch64-none-linux-android21 
--gcc-toolchain=C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 
--sysroot=C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DANDROID -DCOCOS2D_DEBUG=1 
-DUSE_FILE32API -I../../../../../../../cocos2d-x -I../../../../../../../cocos2d-x/cocos -I../../../../../../../cocos2d-x/extensions 
-I../../../../../../../cocos2d-x/cocos/platform -I../../../../../../../cocos2d-x/cocos/editor-support -I../../../../../../../cocos2d-x/cocos/editor-support/fairygui 
-I../../../../../../../cocos2d-x/external/libogg -I../../../../../../../cocos2d-x/external/libvorbis 
-I../../../../../../../cocos2d-x/external/minimp3 -I../../../../../../../cocos2d-x/external/libvorbis/. 
-I../../../../../../../cocos2d-x/external/libvorbis/./lib -I../../../../../../../cocos2d-x/external/libvorbis/../libogg 
-I../../../../../../../cocos2d-x/external/libogg/. -I../../../../../../../cocos2d-x/external/faad2/. -I../../../../../../../cocos2d-x/external/faad2/./include 
-I../../../../../../../cocos2d-x/external/faad2/./libfaad -I../../../../../../../cocos2d-x/external/recast/.. -I../../../../../../../cocos2d-x/external/tinyxml2/. 
-I../../../../../../../cocos2d-x/external/xxhash/. -I../../../../../../../cocos2d-x/external/xxtea/. -I../../../../../../../cocos2d-x/external/clipper/. 
-I../../../../../../../cocos2d-x/external/edtaa3func/. -I../../../../../../../cocos2d-x/external/ConvertUTF/. -I../../../../../../../cocos2d-x/external/poly2tri/.. 
-I../../../../../../../cocos2d-x/external/md5/.. -IC:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/sources/android/cpufeatures 
-I../../../../../../../cocos2d-x/external/unzip/. -isystem ../../../../../../../cocos2d-x/external/OpenAL/include -isystem ../../../../../../../cocos2d-x/external/Box2D/include 
-isystem ../../../../../../../cocos2d-x/external/chipmunk/include -isystem ../../../../../../../cocos2d-x/external/freetype2/include/android/freetype2 
-isystem ../../../../../../../cocos2d-x/external/bullet/include -isystem ../../../../../../../cocos2d-x/external/bullet/include/bullet 
-isystem ../../../../../../../cocos2d-x/external/jpeg/include/android -isystem ../../../../../../../cocos2d-x/external/webp/include/android 
-isystem ../../../../../../../cocos2d-x/external/websockets/include/android -isystem ../../../../../../../cocos2d-x/external/openssl/include/android 
-isystem ../../../../../../../cocos2d-x/external/curl/include/android -isystem ../../../../../../../cocos2d-x/external/png/include/android 
-isystem ../../../../../../../cocos2d-x/external/zlib/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables 
-fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -O0 -fno-limit-debug-info -fno-experimental-isel 
-fPIC -std=c++11 -Winvalid-pch -Xclang -include-pch -Xclang 
D:/GameProject/test/test/frameworks/runtime-src/proj.android/app/.cxx/Debug/1g4z6921/arm64-v8a/engine/cocos/core/CMakeFiles/cocos2d.dir/cmake_pch.hxx.pch -Xclang -include -Xclang
D:/GameProject/test/test/frameworks/runtime-src/proj.android/app/.cxx/Debug/1g4z6921/arm64-v8a/engine/cocos/core/CMakeFiles/cocos2d.dir/cmake_pch.hxx -fpch-preprocess -v -dD
-E Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617)
(https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn) Target: aarch64-none-linux-android21
Thread model: posix InstalledDir: C:\Users\admin\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin Found candidate GCC installation:
C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android\4.9.x Selected GCC installation:
C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x Candidate multilib: .;@m64 Selected multilib:
.;@m64 clang++: warning: argument unused during compilation: '-Wa,--noexecstack' [-Wunused-command-line-argument]
"C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\ndk\\20.1.5948944\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple aarch64-none-linux-android21
-E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name compiler-file10787912169952087600 -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim
-masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1
-fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections -resource-dir
"C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\ndk\\20.1.5948944\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7"
-isystem ../../../../../../../cocos2d-x/external/OpenAL/include -isystem ../../../../../../../cocos2d-x/external/Box2D/include
-isystem ../../../../../../../cocos2d-x/external/chipmunk/include -isystem ../../../../../../../cocos2d-x/external/freetype2/include/android/freetype2
-isystem ../../../../../../../cocos2d-x/external/bullet/include -isystem ../../../../../../../cocos2d-x/external/bullet/include/bullet
-isystem ../../../../../../../cocos2d-x/external/jpeg/include/android -isystem ../../../../../../../cocos2d-x/external/webp/include/android
-isystem ../../../../../../../cocos2d-x/external/websockets/include/android -isystem ../../../../../../../cocos2d-x/external/openssl/include/android
-isystem ../../../../../../../cocos2d-x/external/curl/include/android -isystem ../../../../../../../cocos2d-x/external/png/include/android
-isystem ../../../../../../../cocos2d-x/external/zlib/include -D ANDROID -D COCOS2D_DEBUG=1 -D USE_FILE32API
-I ../../../../../../../cocos2d-x -I ../../../../../../../cocos2d-x/cocos -I ../../../../../../../cocos2d-x/extensions -I ../../../../../../../cocos2d-x/cocos/platform
-I ../../../../../../../cocos2d-x/cocos/editor-support -I ../../../../../../../cocos2d-x/cocos/editor-support/fairygui -I ../../../../../../../cocos2d-x/external/libogg
-I ../../../../../../../cocos2d-x/external/libvorbis -I ../../../../../../../cocos2d-x/external/minimp3 -I ../../../../../../../cocos2d-x/external/libvorbis/.
-I ../../../../../../../cocos2d-x/external/libvorbis/./lib -I ../../../../../../../cocos2d-x/external/libvorbis/../libogg -I ../../../../../../../cocos2d-x/external/libogg/.
-I ../../../../../../../cocos2d-x/external/faad2/. -I ../../../../../../../cocos2d-x/external/faad2/./include -I ../../../../../../../cocos2d-x/external/faad2/./libfaad
-I ../../../../../../../cocos2d-x/external/recast/.. -I ../../../../../../../cocos2d-x/external/tinyxml2/. -I ../../../../../../../cocos2d-x/external/xxhash/.
-I ../../../../../../../cocos2d-x/external/xxtea/. -I ../../../../../../../cocos2d-x/external/clipper/. -I ../../../../../../../cocos2d-x/external/edtaa3func/.
-I ../../../../../../../cocos2d-x/external/ConvertUTF/. -I ../../../../../../../cocos2d-x/external/poly2tri/.. -I ../../../../../../../cocos2d-x/external/md5/..
-I C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/sources/android/cpufeatures -I ../../../../../../../cocos2d-x/external/unzip/. -D
ANDROID -D ___CIDR_DEFINITIONS_END -isysroot C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot
-internal-isystem C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem
C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-isystem
"C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\ndk\\20.1.5948944\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7\\include"
-internal-externc-isystem C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android
-internal-externc-isystem C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem
C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -O0 -Wformat -Winvalid-pch -std=c++11 -fdeprecated-macro -fdebug-compilation-dir
"D:\\GameProject\\test\\test\\frameworks\\runtime-src\\proj.android\\app\\.cxx\\Debug\\1g4z6921\\arm64-v8a"
-ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -dD -include-pch
D:/GameProject/test/test/frameworks/runtime-src/proj.android/app/.cxx/Debug/1g4z6921/arm64-v8a/engine/cocos/core/CMakeFiles/cocos2d.dir/cmake_pch.hxx.pch -include
D:/GameProject/test/test/frameworks/runtime-src/proj.android/app/.cxx/Debug/1g4z6921/arm64-v8a/engine/cocos/core/CMakeFiles/cocos2d.dir/cmake_pch.hxx -o - -x c++
"C:\\Users\\admin\\AppData\\Local\\Temp\\compiler-file10787912169952087600" -mllvm -global-isel=0 clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-w64-windows-gnu error:
unable to read PCH file D:/GameProject/test/test/frameworks/runtime-src/proj.android/app/.cxx/Debug/1g4z6921/arm64-v8a/engine/cocos/core/CMakeFiles/cocos2d.dir/cmake_pch.hxx.pch:
'No such file or directory' ignoring nonexistent directory "C:/Users/admin/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include"
ignoring duplicate directory "../../../../../../../coc ...

编译的时候抛c/c++ configuration problem，详细能看到的就上面那些，后面不知道是不是还省略了一部分。
打包的时候就会报
* What went wrong:
Execution failed for task ':cwdz:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\GameProject\CWDZ11\CWDZ11\frameworks\runtime-src\proj.android\app\.cxx\Debug\1g4z6921\arm64-v8a'

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\admin\\AppData\\Local\\Android\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\GameProject\\test\\test\\frameworks\\runtime-src\\proj.android\\app\\.cxx\\Debug\\1g4z6921\\arm64-v8a" ^
        cocos2dlua
    from D:\GameProject\CWDZ11\CWDZ11\frameworks\runtime-src\proj.android\app
  ninja: error: '../../../../../../../cocos2d-x/external/OpenAL/prebuilt/android/arm64-v8a/libopenal.a', needed by '../../../../build/intermediates/cxx/Debug/1g4z6921/obj/arm64-v8a/libcocos2dlua.so', missing and no known rule to make it

在本地两台win10的机器上运行都是同样的结果，这是cmake配置有问题吗？麻烦大佬帮忙看看

**Comment by 794364474** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by colorwu76** [comment]
> 你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

已经解决了，不用麻烦大佬了
