### ISSUE TITLE
新windows 7 系统解压后运行setup_win.bat后，player3.exe没有历史记录

### ISSUE THREAD

**Issue by wijat** [u0u0/Quick-Cocos2dx-Community#23]
每次开都是一片空白，特此发一个Issues，因为每次重新导入项目，我这样用的很蛋疼。。

![qq 20151202114635](https://cloud.githubusercontent.com/assets/8220843/11521815/370bc12c-98eb-11e5-9094-3321bee1d7b7.jpg)

**Comment by u0u0** [comment]
mark，确实有这个问题，找到重现的环境，就能做手解决。

**Comment by u0u0** [comment]
重现了环境，是中文路径的问题，将在3.6.1中fix。
