### ISSUE TITLE
player 下沒有執行檔，不能開啟。

### ISSUE THREAD

**Issue by timloo0710** [u0u0/Quick-Cocos2dx-Community#27]
也沒有player3.exe. 
沒法開啟。

而在vs2015 community版，打開，proj.win32, 
用player.sln開啟，
build　player3. 

有錯誤訊息，
1>..\network\SocketIO.cpp(442): error C2039: 'back_inserter': is not a member of 'std'
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(12): note: see declaration of 'std'
1>..\network\SocketIO.cpp(442): error C3861: 'back_inserter': identifier not found
2>------ Build started: Project: player3, Configuration: Debug Win32 ------
2>LINK : fatal error LNK1104: cannot open file 'libcurl.lib'
========== Build: 0 succeeded, 2 failed, 3 up-to-date, 0 skipped ==========

請問libcurl.lib，該如何設置?

謝謝!!

**Comment by u0u0** [comment]
player3.exe 在http://www.tairan.com/engines-download 这里下的发布版本里有。

vs2015 编译确实有错，看起来是std库有变动。建议用vs2013编译。
