### ISSUE TITLE
建议创建新工程的时候，不要直接引用"%QUICK_V3_ROOT% 目录下的工程

### ISSUE THREAD

**Issue by lbfamous** [u0u0/Quick-Cocos2dx-Community#30]
如果一个操作系统下存在多个版本的工程，想我的项目除了当前社区版本，目前存在quick-3.3-fina 的版本，这样子工程那个就比较麻烦了，个人建议修改成把cocos 拷贝到工程目录下，这样子每个项目是可以互不干扰的。

**Comment by u0u0** [comment]
双模版难维护，引用方式多项目体量更小。暂不采纳。
