### ISSUE TITLE
chipmunk异常

### ISSUE THREAD

**Issue by grayflow** [u0u0/Quick-Cocos2dx-Community#36]
以下的commit会导致chipmunk在iphone上表现异常：

diff --git a/external/chipmunk/include/chipmunk/chipmunk_types.h b/external/chipmunk/include/chipmunk/chipmunk_types.h
index fdfb6d1..9ed2339 100644
--- a/external/chipmunk/include/chipmunk/chipmunk_types.h
+++ b/external/chipmunk/include/chipmunk/chipmunk_types.h
@@ -5,9 +5,9 @@
    #include "TargetConditionals.h"
 #endif

-//#if ((TARGET_OS_IPHONE == 1) || (TARGET_OS_MAC == 1)) && (!defined CP_USE_CGPOINTS)
-//     #define CP_USE_CGPOINTS 1
-//#endif
+#if ((TARGET_OS_IPHONE == 1) || (TARGET_OS_MAC == 1)) && (!defined CP_USE_CGPOINTS)
-       #define CP_USE_CGPOINTS 1
  +#endif

...

**Comment by u0u0** [comment]
具体是什么异常呢？

**Comment by grayflow** [comment]
iphone6真机

有一堆球同时从屏幕上方不同的位置缓慢掉落，碰到屏幕底部的一条线会破灭；
1. 使用官方的quick3.3final，表现正常，即只有碰撞到底线的球才会破灭；
2. 使用社区版，只要有一个球碰到底线了，所有还在掉落中的球都会破灭（包括尚未触碰底线的）；
3. 使用社区版，但是external/chipmunk/prebuilt/ios/libchipmunk.a这个库使用官方版的, 表现正常；

我diff过两个版本与物理引擎相关的代码，目前看到的就只有上面的区别
社区版版本号:`2a5653048b39f2bb66850ce1e297b0da3f1239e4`

**Comment by u0u0** [comment]
麻烦把test code 发到 175359869@qq.com
或直接加QQ ： 175359869  交流。

**Comment by u0u0** [comment]
accept and closed.
https://github.com/iTyran/Quick-Cocos2dx-Community/commit/e14b8b621477610fdcde3799cc748653ce70eaff
