### ISSUE TITLE
QuickHTTPInterface.java 与最后版本的quick不一致

### ISSUE THREAD

**Issue by kawaiSky** [u0u0/Quick-Cocos2dx-Community#39]
却少
http.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
等代码

**Comment by u0u0** [comment]
哪个版本的quick？ quick 3.5？

**Comment by kawaiSky** [comment]
抱歉没看到，回复晚了。
廖大分支的v3quick最终版
https://github.com/dualface/v3quick/blob/v3/quick/templates/shared/frameworks/runtime-src/proj.android/src/org/cocos2dx/lib/QuickHTTPInterface.java

**Comment by u0u0** [comment]
QuickHTTPInterface 爆出的兼容性问题很多，考虑去掉直接使用curl。
