### ISSUE TITLE
RenderTexture的异步command会导致闪退

### ISSUE THREAD

**Issue by wavestone** [u0u0/Quick-Cocos2dx-Community#42]
RenderTexture的command执行是异步的，但是RenderTexture会被移出舞台而销毁，这时候异步执行的commond会碰到一个空指针，导致闪退。

具体例子见
http://www.cnblogs.com/wantnon/p/4403401.html

希望下个版本能把autorelease绑定放出来

**Comment by u0u0** [comment]
的确RenderTexture的visit后，绘制是在下一帧。
retain和release在lua层是可以调用的。手动retain、release来解决。
