### ISSUE TITLE
为什么beta1 luajit64关闭了JIT,  beta2打开了?

### ISSUE THREAD

**Issue by springrider** [u0u0/Quick-Cocos2dx-Community#45]
请问下这个是什么原因？ 有什么区别吗？ 谢谢！

**Comment by springrider** [comment]
Quick-Cocos2dx-Community/quick/bin/mac/luajit64
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: OFF

Quick-Cocos2dx-Community/quick/bin/mac/luajit64
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse

@u0u0

**Comment by u0u0** [comment]
并未修改编译选项，如果beta1 在64位上关闭了jit，那么就是luajit自己默认就是关闭的，
可能beta2 已经ok了，官方就打开了。

**Comment by springrider** [comment]
看到说明了，谢谢 :+1:
