### ISSUE TITLE
Label：使用更大字体，然后成比例缩小后会导致字体位置出现偏移

### ISSUE THREAD

**Issue by Zieng** [u0u0/Quick-Cocos2dx-Community#50]
在未进行大字体和缩小操作时，字体显示位置正常，但是比如说改为采取2倍的字体大小创建一个label，然后设置`setScale(0.5f)`，然后文字部分就会出现整体的偏移。

**Comment by u0u0** [comment]
锚点的问题？

**Comment by Zieng** [comment]
好像是，不好意思太久了，很早之前解决了这个问题，现在忘了当时的原因是什么了。。。
