### ISSUE TITLE
获取语言ID问题

### ISSUE THREAD

**Issue by liqiangpro** [u0u0/Quick-Cocos2dx-Community#52]
Cocos2dConstants.lua

cc.LANGUAGE_DUTCH      = 6
cc.LANGUAGE_RUSSIAN    = 7
cc.LANGUAGE_KOREAN     = 8
cc.LANGUAGE_JAPANESE   = 9
cc.LANGUAGE_HUNGARIAN  = 10
cc.LANGUAGE_PORTUGUESE = 11
cc.LANGUAGE_ARABIC     = 12

6号开始缺失cc.LANGUAGE_DUTCH，cc.LANGUAGE_RUSSIAN开始，后面的ID依次加1

**Comment by u0u0** [comment]
accpet ,  https://github.com/iTyran/Quick-Cocos2dx-Community/commit/39448af668754fe16d3aebaeb5da502fa86af4a4
