### ISSUE TITLE
runtime-src iOS模拟器奔溃，真机正常

### ISSUE THREAD

**Issue by losingle** [u0u0/Quick-Cocos2dx-Community#54]
{
    gl.supports_vertex_array_object: true
    cocos2d.x.version: Quick-Cocos2dx-Community 3.6.3 Release
    gl.vendor: Apple Inc.
    gl.supports_PVRTC: true
    gl.renderer: Apple Software Renderer
    cocos2d.x.compiled_with_profiler: false
    gl.max_texture_size: 4096
    gl.supports_ETC1: false
    gl.supports_BGRA8888: false
    cocos2d.x.build_type: DEBUG
    gl.supports_discard_framebuffer: true
    gl.supports_NPOT: true
    gl.supports_ATITC: false
    gl.max_samples_allowed: 4
    gl.max_texture_units: 8
    cocos2d.x.compiled_with_gl_state_cache: true
    gl.supports_S3TC: false
    gl.version: OpenGL ES 2.0 APPLE-12.4.2
}

**Comment by u0u0** [comment]
http://tairan.com/archives/10561/
第一条看了吗？

**Comment by losingle** [comment]
按照这条处理，没问题了，不好意思。
感谢。
