### ISSUE TITLE
 运行错误，没有生成player3

### ISSUE THREAD

**Issue by lcrjeff** [u0u0/Quick-Cocos2dx-Community#72]
![54edc6bd-f009-44c9-a68d-3bbfbadf9762](https://cloud.githubusercontent.com/assets/2390203/23735711/4293ba7e-04c2-11e7-85f7-3e16748885b3.png)

**Comment by u0u0** [comment]
这里：http://www.cocos2d-lua.org/download/index.md 下载的才编译了player。
github不放player二进制。

**Comment by lcrjeff** [comment]
好的，谢谢
