### ISSUE TITLE
热更新失败

### ISSUE THREAD

**Issue by lindxsea** [u0u0/Quick-Cocos2dx-Community#74]
输出提示：
[LUA-print] 发现新版本，开始升级        1.0.1
[LUA-print] [INFO] 游戏更新(5):, assetId->@manifest, percent->-1.#INF, percentBy
File->0, message->
[LUA-print] 正在更新文件 :      @manifest
[LUA-print] [INFO] 游戏更新(3):, assetId->, percent->-1.#INF, percentByFile->0,
message->
[LUA-print] 发现新版本，开始升级        1.0.1
[LUA-print] [INFO] 游戏更新(5):, assetId->, percent->0, percentByFile->0, messag
e->Start to update 3 files from remote package.
[LUA-print] 正在更新文件 :
[LUA-print] [INFO] 游戏更新(5):, assetId->, percent->1.#INF, percentByFile->0, m
essage->
[LUA-print] 正在更新文件 :
[LUA-print] [INFO] 游戏更新(7):, assetId->res/project.manifest, percent->1.#INF,
 percentByFile->0, message->Unable to download file
[LUA-print] 更新过程中遇到错误
[LUA-print] [INFO] 游戏更新(7):, assetId->res/up2.png, percent->1.#INF, percentB
yFile->0, message->Unable to download file
[LUA-print] 更新过程中遇到错误
[LUA-print] [INFO] 游戏更新(7):, assetId->res/version.manifest, percent->1.#INF,
 percentByFile->0, message->Unable to download file
[LUA-print] 更新过程中遇到错误
[LUA-print] [INFO] 游戏更新(9):, assetId->, percent->1.#INF, percentByFile->0, m
essage->

**Comment by u0u0** [comment]
文档中提到的服务器开没。
