### ISSUE TITLE
社区版是否考虑加入 GAF ？

### ISSUE THREAD

**Issue by Maxize** [u0u0/Quick-Cocos2dx-Community#75]
现在有个需求想直接使用 swf 导出动画给项目使用，找了一下，发现  [GAF](https://gafmedia.com/)  还是不错的，想问一下是否考虑加进去么？ 
接入参考： [Cocos2dxGAFPlayer](https://github.com/CatalystApps/Cocos2dxGAFPlayer/tree/gaf-4.0)

**Comment by u0u0** [comment]
不会加入。
