### ISSUE TITLE
Need #define snprintf _snprintf on Windows VC2013 编译出错解决

### ISSUE THREAD

**Issue by MR-L-2015** [u0u0/Quick-Cocos2dx-Community#77]
ccMacros.h

#ifdef _MSC_VER
#define snprintf _snprintf
#endif

player.sln用VC2013打开后，把五个工程的工具集设置成vc12_xp后，编译后说snprintf找不到。上面是修改方法

编译通过，连接错误。有些lib使用vc2015预先编译，郁闷，我的368机器没空间安装vc2015了。

**Comment by u0u0** [comment]
以及放弃vs2013的支持，请使用vs2015测试
