### ISSUE TITLE
cc.uiloader:seekNodeByName返回nil

### ISSUE THREAD

**Issue by chenyu0532** [u0u0/Quick-Cocos2dx-Community#80]
用这个来查找cocostudio节点的时候，一直返回nil

**Comment by u0u0** [comment]
cc.uiloader 这个模块即将去掉。
ccui.Helper:seekWidgetByName可以用。只查找widget。

**Comment by guotong1988** [comment]
cc.uiloader替换成什么了？

**Comment by guotong1988** [comment]
替换成了 cc.CSLoader:getInstance():createNodeWithFlatBuffersFile
