### ISSUE TITLE
继承dragonbones

### ISSUE THREAD

**Issue by chenyu0532** [u0u0/Quick-Cocos2dx-Community#81]
环境:win10 64位   vs2013
完全按照tools/tolua下的readme配置，增加dragonbones.ini 修改genbindings.py 拷贝dragonbonescpp  生成lua绑定的时候产生docsunix不是内部或外部命令的错误

**Comment by u0u0** [comment]
我不认为 自动绑定工具能解决 lua接口导出，所以这套工具在3.7中去掉，也不会去开发一个替代品。
手动绑定，知己知彼才能绑定出完美的接口。
目前暂时没有时间去集成dragonbones，毕竟已经有spine了。

**Comment by chenyu0532** [comment]
明白，肯定要懂得怎么去根据自己的需求绑是最关键的。
但是即使不加第三方的库，只根据readme里面的配置描述去重新生成下已经生成的cpp hpp一样会出错误，这就不对了吧
