### ISSUE TITLE
ios编译成功后运行奔溃

### ISSUE THREAD

**Issue by winterfeel** [u0u0/Quick-Cocos2dx-Community#82]
ios下使用3.6.5版本新建项目后编译，编译成功，但是运行的时候奔溃，错误出现在CCLuaStack.cpp的第130行：
`bool LuaStack::init(void)
{
    _state = lua_open();
    luaL_openlibs(_state);`
我不太会调试，只是看到_state为NULL，并下载了git上最新的代码测试仍旧这个bug。
我的xcode是8.2.1，ios sdk 是10.2

**Comment by u0u0** [comment]
是iOS模拟器吧，看这里。http://cocos2d-lua.org/doc/luajit/index.md
另外xcode 8.2 需要替换这个liajit库。
http://cocos2d-lua.org/download/patch/3-6-5.md

**Comment by shengdoushi** [comment]
3.7.2. xcode 9.4.1 依然有这个问题，问题是现在默认安装的模拟器最低已经是 5s 了， 可以默认开启 -pagezero_size 10000 -image_base 100000000 了吧
