### ISSUE TITLE
3.6在android真机，看不到clippingNode遮罩透明

### ISSUE THREAD

**Issue by abab99** [u0u0/Quick-Cocos2dx-Community#83]
就是透明部分还是当有颜色显示了，怎么办？
就是并没有遮罩只是裁剪了图片而已，图片是按矩形裁剪的，不是按模板的不透明（或者说>0.05）的区域裁剪，在pc正常，但是在Android真机及其模拟器，均只是矩形裁剪

**Comment by u0u0** [comment]
clippingNode的问题是比较多，建议写shader来裁剪。
