### ISSUE TITLE
pageview:scrolltopage

### ISSUE THREAD

**Issue by chenyu0532** [u0u0/Quick-Cocos2dx-Community#84]
363中，cocostudio2.0.6,获取完pageview之后运行scrollToPage会发生偏移，而且会有快速翻页的那种效果

**Comment by u0u0** [comment]
完整测试代码。

**Comment by chenyu0532** [comment]
随便建一个layer，在layer初始化里载入pageview的csb，直接调用scrollToPage(xxxx)就能看到

**Comment by u0u0** [comment]
加千人群找我哈，最近比较忙，最好有demo我直接跑了测试。
