### ISSUE TITLE
使用 ByteArray 的时候，readChar() 如果是 -1 的时候返回的是 255

### ISSUE THREAD

**Issue by Maxize** [u0u0/Quick-Cocos2dx-Community#89]
测试了一下，在 player 没有问题，但是跑 android 真机的时候出现了。
网上查了一下，说是在 Android.mk 文件中加入 -fsigned-char 编译就好了， 不过我看了一下代码，是已经加上了的，请问有其他人遇到么？
有一个比较偷懒的方式，但是我不太想用，就是回过头使用 readByte() 然后超过 127 的都减去 256 来求得负值范围。

**Comment by u0u0** [comment]
-fsigned-char 是加了的，readByte（）你可以群里面问下。我没用这个模块，自定义的数据协议。
