### ISSUE TITLE
ios11 Call to unavailable function 'system': not available on iOS

### ISSUE THREAD

**Issue by zacharyhu** [u0u0/Quick-Cocos2dx-Community#91]
void AssetsManager::destroyStoragePath()
{
    // Delete recorded version codes.
    deleteVersion();
    
    // Remove downloaded files
#if (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32)
    string command = "rd /s /q ";
    // Path may include space.
    command += "\"" + _storagePath + "\"";
    system(command.c_str());
#else
    string command = "rm -r ";
    // Path may include space.
    command += "\"" + _storagePath + "\"";
    **_system(command.c_str());_**
#endif

Call to unavailable function 'system': not available on iOS
iOS好像弃用了这个方法，cocos官方修复是用nftw.

**Comment by u0u0** [comment]
AssetsManager已在3.7中去掉了。
而平台层的次方法是正确的。
