### ISSUE TITLE
请问是在哪个版本开始支持IOS64位开发的？

### ISSUE THREAD

**Issue by piccolopegaso** [u0u0/Quick-Cocos2dx-Community#92]
你好，非常感谢你们对开源世界作出的贡献和努力。我看到Quick-Cocos2dx-Community在3.6.2Beta版时就已经使用了LuaJIT 2.1.0， 然后在3.6.4 Release 版本更新说明里说有支持 Luajit 64一项，想请问下到底是哪个版本开始支持64位的？谢谢。

**Comment by piccolopegaso** [comment]
Hi, Can anyone see this? Give me a reply please, thanks.

**Comment by u0u0** [comment]
3.6.0开始
